Repository Automattic/vip-go-node, pull requests merged in 2018-08, with the labels that each got.

#10 Update Logger API to match other module
  __tests__/logger.tests.js
  src/logger/README.md
  src/logger/index.js
Labels: [Status] Needs Review

#8 Add HTTP server module
  .eslintrc
  __tests__/server.tests.js
  package-lock.json
  package.json
  src/server/README.md
  src/server/index.js
Labels: [Status] Has Feedback

#11 Prepare module for publishing in npm
  .npmignore
  .publishrc
  index.js
  package-lock.json
  package.json
Labels: [Status] Ready to Merge

#13 Add Circle CI config
  .circleci/config.yml
  package.json
Labels: [Status] Has Feedback

#14 Add a general README for project
  README.md
  src/logger/README.md
Labels: [Status] Needs Review

#15 Bumping version after publication and adding contribution guidelines
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: [Status] Needs Review

#17 Server: fix invalid logger level
  src/server/index.js
Labels: [Status] Needs Review

#21 Add ES5 transpiler before pushing to npm
  .gitignore
  .npmignore
  .publishrc
  index.js
  package-lock.json
  package.json
  src/index.js
Labels: [Status] Ready to Merge

#24 Fix bug in linting
  .eslintignore
  package.json
Labels: [Status] Ready to Merge

#18 Add VIP_GO_APP_ID and IS_VIP_GO_ENV when deciding which environment
  src/logger/index.js
Labels: [Status] Needs Review

#22 Fix headers already sent error
  .eslintrc
  __tests__/server.tests.js
  src/server/index.js
Labels: [Status] Ready to Merge

#25 Fix logging format
  .eslintrc
  __tests__/logger.tests.js
  src/logger/index.js
Labels: [Status] Ready to Merge
